//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchDetail
    {
        public int SearchID { get; set; }
        public string SearchString { get; set; }
        public string SearchPath { get; set; }
    }
}
